language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - gcc-5
      - g++-5

env:
  - CONF=--disable-output-edi
  - CONF=
  - CONF=--enable-input-prbs --enable-input-test --enable-input-udp --enable-output-raw
  - CONF=--disable-format-raw --disable-format-mpeg --disable-format-packet --disable-format-dabplus --disable-format-dmb --disable-format-epm --disable-input-fifo --disable-input-file

compiler:
  - gcc

script:
  - |
    ./bootstrap.sh
    CC=gcc-5 CXX=g++-5 ./configure $CONF
    make

