language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - g++-6

env:
  - CONF=--disable-output-edi
  - CONF=
  - CONF=--enable-output-raw

compiler:
  - gcc

script:
  - |
    ./bootstrap.sh
    CC=gcc-6 CXX=g++-6 ./configure $CONF
    make

